<a href="https://colab.research.google.com/github/rvishakhs/Deep_Learning/blob/Fundamentals/00_tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow



1. Introduction to tensors
2. Getting information from tensors
3. Manipulating tensors
4. Tensors & Numpy
5. Using @tf.function (a way to spped up your regular Python functions)
6. Using GPUs with TensorFLow (or TPUs)
7. Exercise to try for yourself





In [2]:
# Impot Tensorflow
import tensorflow as tf
print(tf.__version__)


2.17.1


In [3]:
# Create tensors with tf.constant()

scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (Same like shape in numpy)
# ndim stands for number of dimensions
scaler.ndim

0

In [6]:
# Create a vector ( like simple array )
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the number of dimensions of a vector
vector.ndim

1

In [11]:
# creating a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
#check the dimention of matrix same as vectors and scaler
matrix.ndim

2

In [13]:
#Create another matrix with different data type
another_matrix = tf.constant([[10.,7],[7.8, 5.],[8.,9]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 7.8,  5. ],
       [ 8. ,  9. ]], dtype=float16)>

In [14]:
#check the dimensions
another_matrix.ndim


2

##Tensors

In [16]:
# Creating a Tensor
tensor = tf.constant([[[1,2,3],[2,5,7]],[[5,4,6],[8,2,3]],[[1,5,4],[4,9,3]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 5, 7]],

       [[5, 4, 6],
        [8, 2, 3]],

       [[1, 5, 4],
        [4, 9, 3]]], dtype=int32)>

In [17]:
tensor.ndim

3

What we've Created so far

1. Scaler: a single number
2. Vector: a number with direction(e.g. wind speed and direction)
3. Matrix: a 2-dimensional array of Numbers
4. Tensor: an n dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scaler and 1-dimensional tensor is a vector, so on)

###Creating Tensors with Tf.Variable

In [19]:
# Create the same tensor with tf.Varible as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [20]:
#let's check can we change the values in Variable
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [21]:
#let's check can we change the values in Constant
unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [23]:
# So from the above code block we can find out only variable can be change numbers assigning to constant is fixed and unchanble

### Creating Random Tensors

In [24]:
# Create two random (but the same ) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibilty
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibilty
random_2 = random_2.normal(shape=(3,2))

# Check if they are equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)