<a href="https://colab.research.google.com/github/rvishakhs/Deep_Learning/blob/main/00_tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow



1. Introduction to tensors
2. Getting information from tensors
3. Manipulating tensors
4. Tensors & Numpy
5. Using @tf.function (a way to spped up your regular Python functions)
6. Using GPUs with TensorFLow (or TPUs)
7. Exercise to try for yourself





In [2]:
# Impot Tensorflow
import tensorflow as tf
print(tf.__version__)


2.17.1


In [3]:
# Create tensors with tf.constant()

scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (Same like shape in numpy)
# ndim stands for number of dimensions
scaler.ndim

0

In [6]:
# Create a vector ( like simple array )
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the number of dimensions of a vector
vector.ndim

1

In [11]:
# creating a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
#check the dimention of matrix same as vectors and scaler
matrix.ndim

2