<a href="https://colab.research.google.com/github/rvishakhs/Deep_Learning/blob/Fundamentals/00_tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow



1. Introduction to tensors
2. Getting information from tensors
3. Manipulating tensors
4. Tensors & Numpy
5. Using @tf.function (a way to spped up your regular Python functions)
6. Using GPUs with TensorFLow (or TPUs)
7. Exercise to try for yourself





In [1]:
# Impot Tensorflow
import tensorflow as tf
print(tf.__version__)


2.17.1


In [2]:
# Create tensors with tf.constant()

scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (Same like shape in numpy)
# ndim stands for number of dimensions
scaler.ndim

0

In [4]:
# Create a vector ( like simple array )
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the number of dimensions of a vector
vector.ndim

1

In [6]:
# creating a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
#check the dimention of matrix same as vectors and scaler
matrix.ndim

2

In [8]:
#Create another matrix with different data type
another_matrix = tf.constant([[10.,7],[7.8, 5.],[8.,9]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 7.8,  5. ],
       [ 8. ,  9. ]], dtype=float16)>

In [9]:
#check the dimensions
another_matrix.ndim


2

##Tensors

In [10]:
# Creating a Tensor
tensor = tf.constant([[[1,2,3],[2,5,7]],[[5,4,6],[8,2,3]],[[1,5,4],[4,9,3]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 5, 7]],

       [[5, 4, 6],
        [8, 2, 3]],

       [[1, 5, 4],
        [4, 9, 3]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've Created so far

1. Scaler: a single number
2. Vector: a number with direction(e.g. wind speed and direction)
3. Matrix: a 2-dimensional array of Numbers
4. Tensor: an n dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scaler and 1-dimensional tensor is a vector, so on)

###Creating Tensors with Tf.Variable

In [12]:
# Create the same tensor with tf.Varible as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#let's check can we change the values in Variable
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
#let's check can we change the values in Constant
unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [15]:
# So from the above code block we can find out only variable can be change numbers assigning to constant is fixed and unchanble

### Creating Random Tensors

In [16]:
# Create two random (but the same ) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibilty
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibilty
random_2 = random_2.normal(shape=(3,2))

# Check if they are equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the Tensors

In [17]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled_tensor = tf.constant([[10,7],[3,4],[5,8]])


In [18]:
not_shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  8]], dtype=int32)>

In [19]:
tf.random.shuffle(not_shuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 5,  8]], dtype=int32)>

It looks like if we want our shuffled tensors to be in the same order, we've got to use the globel level and opeartional level

In [20]:
# example

tf.random.set_seed(42) # Gobel level random seed
tf.random.shuffle(not_shuffled_tensor,seed=42) # Operation level random seed


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  8]], dtype=int32)>

### Other ways to make tensors

In [21]:
# Let's create tensors with all one (like numpy ones)
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
# Create a random tensor with all zeros
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy Array into tensors

The main difference between Numpy arrays and Tensorflow Tensors is that tensors can be run on a GPU for faster computing


In [23]:
# Turning Numpy array to into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create a Numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
#Let's try to convert the same numpy array into tensors
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [25]:
# If we want we can change the shape of a tensor at the same time we converting them like:
tensor_B = tf.constant(numpy_A, shape=(2,3,4))
tensor_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [26]:
# Another Example
tensor_c = tf.constant(numpy_A, shape=(3,8))
tensor_c

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

### Getting Information from Tensors

when dealing with tensors you probably want to be aware of the following

1. Shape
2. Rank
3. Axis or dimension
4. Size

In [27]:
# Creating a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Extract only the first index from the above tensor
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
# Get some basic information about the tensors
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
# Add in extra dimension in our tensor
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [31]:
#Normal numpy array
some_list = [1,2,3,4]
some_list

[1, 2, 3, 4]

In [32]:
some_list[-1]

4

In [33]:
#Display last two elements from each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [34]:
# Add in extra dimension to our rank_2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [35]:
 #Alternatives to tf.newaxis
 tf.expand_dims(rank_2_tensor,axis = -1) # " -1 means from the final axis"


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulatring tensors (Tensor Operations)

# Basic Operations

In [37]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [38]:
# Things to not is that we must declare to variable unless the orginal value remains same
tensor

# In order to get the change

tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
# We can use the build in tensor flow functions for maths operations
tf.add(tensor,10)

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [40]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Matrix Multiplication

In [41]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [42]:
tensor_1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_2 = tf.constant([[3,5],[6,7],[1,8]])

In [43]:
tensor_1, tensor_2


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [44]:
tensor_3 = tf.matmul(tensor_1,tensor_2)
tensor_3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

### Matrix multiplication rules
In Machine learning, matrix multiplication is one of the most common tensor operations.

These are the two golden riles of our tensor multiplication

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions.

### The dot Product

Matric multiplication is also referred as the dot product

You can perform matrix multiplication using

1. 'tf.matmul()'
2. tf.tensordot()

In [45]:
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])

In [46]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [47]:
# Perform the dot product on X and Y (requires X or Y to be transponded)

tf.tensordot(tf.transpose(X), Y , axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [48]:
# Perform matrix multiplication between X and Y(transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [49]:
tf.transpose(Y)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [50]:
#Let's Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
# Check the values of Y, reshape Y and transposed Y

print("Normal Y: ")
print(Y,"\n") # "\n is for new line"

print("Y reshaped to (2, 3): ")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two twnsors and one of the axes doesn't lineup, ypu will transpose(rather than reshaping) one of the tensors to get satsify the matrix multiplication rules.



### Agregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [52]:
D = tf.constant([7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([  7, -10], dtype=int32)>

In [53]:
# Now get the absolute Values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation
1. Get the minimum
2. Get the maximum
3. Get the mean of a tensor
4. Get the sum of a tensor




In [54]:
tensor = tf.constant(np.random.randint(0,100,size=10))
tensor

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([64,  3, 36, 55, 91, 68, 76, 58, 43, 66])>

In [55]:
tensor

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([64,  3, 36, 55, 91, 68, 76, 58, 43, 66])>

In [56]:
#Get the minimum
tf.math.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [57]:
#Get the Maximum
tf.math.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=91>

In [58]:
#Get the mean of a tensor
tf.math.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [59]:
#Let's find the sum of a tensor
tf.math.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=560>

In [60]:
# FInd the varience of our tensor
# To find the varience of a tensor we need to import tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=531>

In [64]:
#Find the standard deviation
tf.math.reduce_std(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=23.056452>

### Finding the Maximum position and minimum position in an axis


In [65]:
# First we need to create an uniform tnesor

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [66]:
# Find the positional Maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [67]:
# Find the value by position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [68]:
# Find the maximum value
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [69]:
# Compare them to know are they equal

assert F[tf.argmax(F)] == tf.reduce_max(F)

In [70]:
# Now find the positional minumum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [71]:
# And find the minimum value using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [72]:
# Find the minimum value using reduce method
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [73]:
# And check for equality

assert F[tf.argmin(F)] == tf.reduce_min(F)

### One hot encoding


In [75]:
# Create a list of colors
colors = [1,2,3,4]

# One hot encoding
tf.one_hot(colors,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>